newfile: Create template for submission
purpleidea/legal-hackers pull request #7
Opened 2018-11-05 23:30 UTC by kappapiana

Created the template for submission to be filled in as a pull request comment

2018-11-05 23:52 UTC, purpleidea requested changes
Great idea once again. File isn't named correctly though. Thanks!

2018-11-05 23:52 UTC, purpleidea commented on .github/.PULL_REQEST_TEMPLATE.md
> +## self assessment:
Let's just have this be the top level category (`Self Assessment:`) and include a small introductory message under it like: "Please fill out the following self assessment."

2018-11-05 23:52 UTC, purpleidea commented on .github/.PULL_REQEST_TEMPLATE.md
> +> Your information goes here (and in the same place below)
What's this line for?

2018-11-05 23:52 UTC, purpleidea commented on .github/.PULL_REQEST_TEMPLATE.md
> +## General information
We can nix this section, see comment below.

2018-11-07 08:27 UTC, kappapiana commented
I think all comments have been addressed.

2018-11-08 00:01 UTC, purpleidea requested changes
Looks pretty close, thanks!
A good practice can be to do a `git show` or `git diff ...` after your patch is ready, but before you push to look it over and see if it's exactly what you expect. Becoming detail oriented (when dealing with annoying programmers) is an invaluable skill! You're well on your way! Thanks for the patch.

2018-11-08 00:01 UTC, purpleidea commented on .github/.PULL_REQUEST_TEMPLATE.md
> +## self assessment:
capitalize please

2018-11-08 00:01 UTC, purpleidea commented on .github/.PULL_REQUEST_TEMPLATE.md
> +Please fill out the following self assessment and provide context: .
why is there a trailing space, period??

2018-11-08 00:01 UTC, purpleidea commented on .github/.PULL_REQUEST_TEMPLATE.md
> +
I don't think we need all the empty newlines between each list item.

2018-11-08 00:02 UTC, purpleidea commented
Also, look at the example here: https://github.com/purpleidea/mgmt/tree/master/.github
Note the difference in how you named your file... (It's currently wrong)

2018-11-08 07:13 UTC, kappapiana commented on .github/.PULL_REQUEST_TEMPLATE.md
> +Please fill out the following self assessment and provide context: .
No F-- idea. corrected

2018-11-18 01:34 UTC, merged

2018-11-18 01:35 UTC, purpleidea commented
LGTM, merged, thanks!

I would have merged sooner, but I didn't realize you had updated the branch. Protip: when you push or force-push, github doesn't notify you, so it's common to also write a little message when ready, eg: "okay, fixed, please review" or something similar. Thanks!